{
  "env": {
    "browser": true,
    "commonjs": true,
    "es6": true,
    "jasmine": true
  },
  "parser": "babel-eslint",
  "extends": [
    "airbnb"
  ],
  "rules": {
    "react/jsx-filename-extension": [ 1, { "extensions": [ ".js", ".jsx" ] } ],
    "comma-dangle": ["error", {
      "arrays": "always-multiline",
      "objects": "always-multiline",
      "imports": "always-multiline",
      "exports": "always-multiline",
      "functions": "always-multiline",
    }]
  }
}
