env:
  browser: true
  commonjs: true
  es6: true
  jasmine: true
parser: 'babel-eslint'
extends:
  - 'airbnb'
  - 'plugin:jasmine/recommended'
  - 'plugin:react/recommended'
parserOptions:
  ecmaFeatures:
    ecmaFeatures.classes: true
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
  - jasmine
