env:
  browser: true
  commonjs: true
  es6: true
extends:
  - 'plugin:jasmine/recommended'
  #- 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
  - jasmine
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  jasmine/no-focused-tests: 0
  jasmine/no-suite-dupes:
    - 2
    - branch
