env:
  browser: true
  commonjs: true
  es6: true
parser: 'babel-eslint'
extends:
  - 'plugin:jasmine/recommended'
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parserOptions:
  ecmaFeatures:
    ecmaFeatures.classes: true
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
  - jasmine
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  jasmine/no-focused-tests: 0
  jasmine/no-suite-dupes:
    - 2
    - branch
