# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c182eb9fdf363e79fd0d89f49c187e650e380567d85a6cb067146e6e5b12b21b33d3e77178cd63101f5d0d30c8ecbabdfdfc866b52ff6e61105cc5f2f75d2b07

test:
  secret_key_base: eb466706ce1a7a96209f0f61d6280e36c3093e180e3845f3d561cf6a4d6d4fd83e62b7fc247728363a38bef8beeaf7091338eae37d066c8556e74dcc5d879bc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
